### ISSUE TITLE
Feature request: Improve image uploading when creating a post

### ISSUE THREAD

**Issue by Tywele** [asimons04/Tesseract#11]
Right now the only way to upload images is to either paste the URL of the image or select an image from my PC to upload. In the default lemmy ui you can also paste an image into the URL field and it gets uploaded automatically. 

Also I don't get a preview of the image when pasting a URL (this would also be useful when it's possible to just paste an image obviously)

Would be nice if this could be added.

**Comment by asimons04** [comment]
> Right now the only way to upload images is to either paste the URL of the image or select an image from my PC to upload. In the default lemmy ui you can also paste an image into the URL field and it gets uploaded automatically.

That's a nice quality-of-life feature, I agree.  The current image upload mechanism already places the file into a `blob:`, so taking the pasted image and putting that into the blob _should_ be doable.  Will have to see what it'll take to integrate that capability into the editor.

> Also I don't get a preview of the image when pasting a URL (this would also be useful when it's possible to just paste an image obviously)

In my current development branch, I've changed the way post previews work.  Instead of just rending the markdown, it runs the post draft through the whole `Post` rendering stack and gives you a true live preview.    Hope to have this completed, tested, and rolled out in the 1.2.62 release.

**Comment by asimons04** [comment]
>Also I don't get a preview of the image when pasting a URL (this would also be useful when it's possible to just paste an image obviously)

Implemented in 1.2.62

>Right now the only way to upload images is to either paste the URL of the image or select an image from my PC to upload. In the default lemmy ui you can also paste an image into the URL field and it gets uploaded automatically.

Please add that in the Discussions section.

**Comment by Tywele** [comment]
Created a discussion here: https://github.com/asimons04/Tesseract/discussions/13
