### ISSUE TITLE
Image uploads failing

### ISSUE THREAD

**Issue by weiteck** [asimons04/tesseract#2]
**What version of Tesseract has this bug?**
v1.2.9.31

**Describe the bug**
403 error when uploading an image to my deployment at [tes.leminal.space](https://tes.leminal.space).

POST requests  going to `https://tes.leminal.space/cors/leminal.space/pictrs/image` instead of `https://leminal.space/pictrs/image`

**To Reproduce**
1. Create post or comment
2. Try to upload an image

**Expected behavior**
A successful image upload.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Pop! OS
 - Browser: Firefox and Chrome
 - Version: 124 and 123

**Smartphone (please complete the following information):**
 - Device: S21
 - OS: Android 13
 - Browser: Firefox
 - Version: 124.1

**Additional context**
I have tried replacing my nginx config with the suggested one from the readme. I have also tried disabling Cloudflare proxy.

I have tested uploads with Lemmy-UI and Photon and they are working fine.

Response as reported by Firefox:
```
XHRPOST
https://tes.leminal.space/cors/leminal.space/pictrs/image?
[HTTP/2 403  3870ms]

	
POST
	https://tes.leminal.space/cors/leminal.space/pictrs/image
Status
403
VersionHTTP/2
Transferred153 B (46 B size)
Referrer Policystrict-origin-when-cross-origin
Request PriorityHighest
DNS ResolutionSystem

    	
    content-length
    	46
    date
    	Sun, 07 Apr 2024 04:10:04 GMT
    server
    	nginx
    X-Firefox-Spdy
    	h2
    	
    Accept
    	*/*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	en-US,en;q=0.5
    Authorization
    	Bearer eyJ ... [redacted] ... EX5s
    Connection
    	keep-alive
    Content-Length
    	222568
    Content-Type
    	multipart/form-data; boundary=---------------------------21285429431615611593375936745
    DNT
    	1
    Host
    	tes.leminal.space
    Origin
    	https://tes.leminal.space
    Referer
    	https://tes.leminal.space/create/post/
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	same-origin
    Sec-GPC
    	1
    TE
    	trailers
    User-Agent
    	Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0
```

**Comment by asimons04** [comment]
Hmm...

The upload to the Tessearct URL is correct and expected behavior (POST -> https://tes.leminal.space/cors/leminal.space/pictrs/image).  There's a server-side component in Tesseract that will proxy uploads from the browser to the target Lemmy server.  This was needed in 0.18.x and below since the Lemmy API didn't do CORS correctly on the `/pictrs/image` path, and image uploads only worked from the same domain as the API.  To work around that, Tesseract proxies that path through itself (since its fetch requests aren't bound by CORS) and uploads it on your behalf (hence the `/cors/{instance}/pictrs/image` path). 

I've been using Tesseract with 0.19.3 and 0.18.5 instances, and uploads are working in both. I just re-tested that against my own instance (0.18.5 for reasons), Discuss Online (0.19.3) and Lemmy World (0.19.3), and all 3 worked. 

Once I drop 0.18.x support, I'll likely remove the proxy behavior since it doesn't seem to be needed in 0.19.

Back to the problem at hand, though.  _Something's_ not right.  I'm barely awake right now, but my gut says it's the Nginx config.

My _guess_ is I left out the proxy pass headers from the example, and those aren't getting passed to the Tesseract backend. 

Try updating the `location` block to something like this:

```
  location / {
    # Adjust as needed, but these are what I have in my dev server
    proxy_http_version              1.1;
    send_timeout                    5m;
    proxy_read_timeout              360;
    proxy_send_timeout              360;
    proxy_connect_timeout           360;
    proxy_max_temp_file_size        0;

    # Set headers to send to backend server
    proxy_set_header  Host                  $host;
    proxy_set_header  X-Forwarded-Host      $host;
    proxy_set_header  X-Forwarded-For       $remote_addr;
    proxy_set_header  X-Forwarded-Proto     $scheme;
    proxy_set_header  X-Forwarded-Uri       $request_uri;
    proxy_set_header  X-Forwarded-Ssl       on;

    # Update this to match the IP/port you are using
    proxy_pass http://127.0.0.1:8080;
  }

```

Let me know if that works, and I'll update the example in the README.  It's pretty bare bones as far as examples go, but it's mostly for illustration purposes since I didn't want to have to make example configs for every reverse proxy option.

**Comment by weiteck** [comment]
Thanks for explaining the proxy behaviour.

Your instinct that it was caused by an nginx config issue was spot on - I tried your config above and uploads worked! This led me to dig into my original config, which had some proxy headers set already, to see which were causing the issue. Turns out it was these:

```
proxy_set_header Upgrade               $http_upgrade;
proxy_set_header Connection            "upgrade";
```

**Comment by asimons04** [comment]
Excellent!  Glad that worked.

I'm _pretty sure_ only the `Host` header is required to be passed, but it's good practice to forward other aspects of the original request as well.  I'll try to confirm that when I have more time.

For now, I just added those proxy directives to the Nginx example in the README for the main branch.
