### ISSUE TITLE
Embedded images are not handled correctly

### ISSUE THREAD

**Issue by db0** [asimons04/tesseract#8]
Maybe caused by the alt-text included in the markdown, but [such posts](https://t.lemmy.dbzer0.com/post/lemmy.dbzer0.com/33311504?thread=0.15363065.15363430.15403274.15404613.15436774.15436784) are not displayed correctly, but [they work in lemmy UI](https://lemmy.dbzer0.com/comment/15436784)

**What version of Tesseract has this bug?**
1.4.20

**Screenshots**

![image](https://github.com/user-attachments/assets/1319dfae-9739-489d-9686-645f4a115c02)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22
 - Browser firefox

**Comment by asimons04** [comment]
Can you provide a link to that comment so I can grab the original text?

**Comment by db0** [comment]
I did. It's hyperlinked in the OP but here it is again: https://lemmy.dbzer0.com/comment/15436784

**Comment by asimons04** [comment]
Fixed in 815fda32

Demo:  https://dev.dubvee.org/post/lemmy.dbzer0.com/33311504?thread=0.15363065.15363430.15403274.15404613.15436774.15436784

Issue was the user link was being badge-ified inside the alt text markdown during the pre-processing step.  Re-wrote pre-processor, added new regex lookbehinds, and also resolved a few other markdown glitches related to code blocks and removed the old regex shims that were previously addressing those edge cases.

**Comment by asimons04** [comment]
FYI:  It would make my life easier (and probably other devs) if there would be spaces or newlines between the images your bot posts:

```
![Image with seed 3240744267 generated via AI Horde through @aihorde@lemmy.dbzer0.com. Prompt: a mob of lemmy peasants carrying pitchforks rising against their AI overlords in violent revolution](https://lemmy.dbzer0.com/pictrs/image/adf1f0aa-bb4f-4612-ac4d-82ba02b88d78.webp)![Image with seed 3240744267 generated via AI Horde through @aihorde@lemmy.dbzer0.com. Prompt: a mob of lemmy peasants carrying pitchforks rising against their AI overlords in violent revolution](https://lemmy.dbzer0.com/pictrs/image/a2677665-8e2c-4325-a32d-48fea1d92ff9.webp)![Image with seed 3240744267 generated via AI Horde through @aihorde@lemmy.dbzer0.com. Prompt: a mob of lemmy peasants carrying pitchforks rising against their AI overlords in violent revolution](https://lemmy.dbzer0.com/pictrs/image/268ec13f-3c29-410f-b716-4d07c5dc7a3d.webp)![Image with seed 3240744267 generated via AI Horde through @aihorde@lemmy.dbzer0.com. Prompt: a mob of lemmy peasants carrying pitchforks rising against their AI overlords in violent revolution](https://lemmy.dbzer0.com/pictrs/image/4a7df1eb-8199-47ba-ae1d-9f90b7447cc3.webp)
```

I tuned up the pre-processor again, and it's rendering almost everything else much better, but it's not handling those *quite* right (though it at least handles them gracefully).

Basically the `@user@instance.xyz` inside of the alt text is still getting turned into a markdown link `[@user@instance.xyz](/u/user@instance.xyz)` but it's not trying to render the action badge (which is what broke them initially).

![image](https://github.com/user-attachments/assets/1e94346d-8445-4977-88a8-71d12a219420)

The first image renders the alt text correctly but for the rest in that unbroken string of image links, the alt text has the markdown link format inside.  I can live with that.  Putting either a space or newline between each image will remedy that.


That said, that's as far as I'm going to go down that rabbit hole since the source text is _technically_ malformed.

**Comment by db0** [comment]
Hm, why do you say the source text is malformed though? iirc missing linebreaks between images is not bad markdown, no?
