### ISSUE TITLE
Allow sending rejection reason to applications

### ISSUE THREAD

**Issue by db0** [asimons04/tesseract#9]
When rejecting a registration application on the Lemmy UI, you can also send back a rejection reason.

**Comment by asimons04** [comment]
Any idea what API version that was introduced in?  I'm building against 19.3 at the moment.

I also may not be able to test that until I upgrade my own instance, just FYI.

**Comment by db0** [comment]
As far as I know, that was available since a long time. It should be there at 19.3 already

**Comment by asimons04** [comment]
Ah, ok, so I was over-thinking this.  I interpreted it as "send an email with the rejection reason" but apparently I don't even have the form element to capture the reason at all.  After digging through multiple branches of the JS client, looks like that's been there since at least 0.18.3, and I've just never implemented it.  I had it confused with the long-requested server feature to email the rejection to the denied applicant. 

I just released 1.4.22 and am currently working on this for 1.4.23. 

Probably going to overhaul the whole `/admin` section in the process:

1) _Try_ to add the 0.19.4+ server/site options _without_ breaking lower API levels.  I'm going to assume if they don't break on my instance, they'll work on newer ones.  

2) Re-Implement the registration application flow to look/feel more like the reports and inbox (that design seems to be working well? Nobody's complained, and I've gotten one compliment on the new inbox design 🤷🏻‍♂️)

  - Add some additional relevant data from the application to the management screen:
    - Registration email address if provided
    - Email verified status
    - Date/time of application
  - Add the deny reason field
  - Add an option when denying to also ban the user with the ban reason set to `Application Denied: {reason}`.  That's useless for security, but useful so it creates a modlog entry for later reference and something the denied user can see.

**Comment by asimons04** [comment]
Completed in current 1.4.23 branch.  Still re-working the admin section's layout/navigation, but the application manager part is completed.  I _may_ have over-engineered it, but I like it :)

One thing that I can't really screenshot is that the new user's name is clickable and brings up the profile modal.  From there, you can search for alt accounts (accounts your instance knows of with the same username) to see if this is someone instance hopping that you may not want on your instance (you can view the submissions of each alt from the search results).

The "Throwaway Email" indicator checks the supplied email address against a list of known, low-hanging-fruit throwaway email providers.  It's only an indicator and has nothing to do with the approval / denial process other than giving the admin information.

I didn't want to do separate screenshots, but it all collapses down nicely for mobile.

**Application List**

**Note**:  The username of the applicant would be shown to the right of the relative date, but those have been blurred out here for privacy.  There's also a third badge type not shown, "Pending", which is grey.  Pending applications are ones that have not been interacted with (approved or denied).  I just don't have any on my instance right now.


![image](https://github.com/user-attachments/assets/6562d934-339f-4a03-8f0c-a36be979e86b)



**New Application View and Action Menu**

![image](https://github.com/user-attachments/assets/9c3a1bbc-188a-4016-b75f-37a2265d3d86)

**Application Approval Menu***

"Approve" just approves the application as usual.  

"Approve + Modlog" will create a modlog entry (instance unban) with the reason set to 'Registration application approved'.   This could be beneficial if emails are not required for signup and/or if they don't receive the approval email for whatever reason.

![image](https://github.com/user-attachments/assets/85dc5709-6a83-4487-b013-e22627719fe9)

**Application Denial Menu**

Can optionally create a modlog entry (ban instance) with the reason set to 'Registration application denied: {SPECIFIED REASON}'.  This could be beneficial if rejection emails are still not being sent, if they didn't provide an email address, and/or if you want to provide an easy way for users to check if and why they were denied.

![image](https://github.com/user-attachments/assets/1a8c772b-dd9e-4a8d-93e8-28be2286d6a8)

**Modlog Entries for the approval (bottom) and denial (top)**

Note that it will take care of banning/unbanning as appropriate. It shows banned because I took that screenshot after.  If the account is banned already (e.g. from a previous/accidental denial), it will automatically unban the account if it is later approved.

![image](https://github.com/user-attachments/assets/aa27ccc2-0ec4-4b2e-9960-dc0ddd5d4b09)

I'll leave this bug open until I have this merged into the version branch.

**Comment by asimons04** [comment]
Completed, merged, and released in 1.4.23.
